### ISSUE TITLE
Keep a changelog in all active repositories

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/.github#4]
Set up a `CHANGELOG.md` file for every repository, following template of: https://keepachangelog.com

repos:
* [x] circles-myxogastria [PR](https://github.com/CirclesUBI/circles-myxogastria/pull/157)
* [x] circles-contracts [PR](https://github.com/CirclesUBI/circles-contracts/pull/117)
* [x] circles-api [PR](https://github.com/CirclesUBI/circles-api/pull/46)
* [x] circles-core [PR](https://github.com/CirclesUBI/circles-core/pull/65)
* [x] circles-docker [PR](https://github.com/CirclesUBI/circles-docker/pull/27)
* [x] safe-relay-service [PR](https://github.com/CirclesUBI/safe-relay-service/pull/31)
* [x] circles-website [PR](https://github.com/CirclesUBI/circles-website/pull/31)
* [x] circles-dashboard [PR](https://github.com/CirclesUBI/circles-dashboard/pull/8)
* [x] circles-handbook [PR](https://github.com/CirclesUBI/circles-handbook/pull/4)
* [x] circles-subgraph [PR](https://github.com/CirclesUBI/circles-subgraph/pull/35)
* [x] circles-transfer [PR](https://github.com/CirclesUBI/circles-transfer/pull/3)
* [x] circles-iac [PR](https://github.com/CirclesUBI/circles-iac/pull/4)
* [x] whitepaper [PR](https://github.com/CirclesUBI/whitepaper/pull/14)
* [x] circles-analysis [PR](https://github.com/CirclesUBI/circles-analysis/pull/3)
* [x] circles-protocol-website [PR](https://github.com/CirclesUBI/circles-protocol-website/pull/2)
* [x] circles-toolbelt [PR](https://github.com/CirclesUBI/circles-toolbelt/pull/1)

**Comment by louilinn** [comment]
@adz Should the changelog files be setup empty, include instructions/templates or even include any history of earlier changes?

**Comment by adzialocha** [comment]
I think we can start from scratch here @louilinn, we can gradually add past releases but I think this is not a requirement for now.

**Comment by louilinn** [comment]
@adzialocha Hey some of the PRs require reviews to merge. Are you ok with merging those?

**Comment by louilinn** [comment]
@adzialocha what about the contracts repo?
And should I delete the whitepaper PR?

**Comment by adzialocha** [comment]
@louilinn yes, agreed, I think we don't need the CHANGELOG in `whitepaper`!
